server:
  port: 8080
  servlet:
    context-path: /
    encoding:
      charset: UTF-8
      enabled: true
      force: true

spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/travary?useUnicode=true&characterEncoding=utf8&autoReconnect=true&serverTimezone=Asia/Seoul&useOldAliasMetadataBehavior=true
    username: sbsst
    password: sbs123414

  jpa:
    hibernate:
      ddl-auto: create #create update none
    properties:
      hibernate:
        show_sql: true
        format_sql: true
        use_sql_comments: true

#  security:
#    oauth2:
#      client:
#        registration:
#          google:
#            client-id: 587791469053-iqlaep1bv3lcl9uhu2abf3q1die6dftj.apps.googleusercontent.com
#            client-secret: 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
#            scope:
#              - email
#              - profile